Lucky::StaticCompressionHandler.configure do |settings|
  # This setting turns off the serving of pre-compressed assets, but they will still
  # be generated by webpack. To disable webpack from compressing remove the
  # compression-webpack-plugin in webpack.mix.js
  settings.enabled = true

  # by default the following file extensions with be compressed
  # .htm .html .txt .css .js .svg .json .xml .otf .ttf .woff .woff2
  # to add additional extensions do something like:
  # config.gzip_file_extensions << ".myext"
end
