#!/usr/bin/env sh

BIN=${BIN:-lucky}
OUTPUT_DIR=${OUTPUT_DIR:-bin}
TARGET=${TARGET:-x86_64-unknown-linux-gnu}

shards install --without-development
crystal build --release --static --no-color -o $OUTPUT_DIR/$BIN --target $TARGET src/lucky.cr