#!/usr/bin/env bash

# Exit if any subcommand fails
set -e
set -o pipefail

if ! command -v docker-compose > /dev/null; then
    printf 'Docker and docker-compose are not installed.\n'
    printf 'See https://docs.docker.com/compose/install/ for install instructions.\n'
    exit 1
fi

cp -n .env.sample .env || true

docker-compose build

docker-compose run --rm app shards install
