#!/usr/bin/env bash

# Exit if any subcommand fails
set -e
set -o pipefail

source ./script/override_shards

function check_print {
    if [ -t 0 ]; then
        printf "$1"
    fi
}

check_print "\nChecking code formatting...\n\n"

if ! crystal tool format --check src spec > /dev/null; then
    check_print "\nCode is not formatted.\n"
    check_print "\nFormat the code with: crystal tool format src spec\n\n"
    exit 1
else
    check_print "\nCrystal format checks passed.\n\n"
fi

if ! crystal ./bin/ameba.cr; then
    check_print "\nCode did not pass Ameba checks.\n"
    check_print "\nResolve Ameba linter errors, then run this checker again\n\n"
    exit 1
else
    check_print "\nAmeba linter checks passed.\n\n"
fi

check_print "\nRunning specs with 'crystal spec'\n\n"
crystal spec "$@"

