#!/usr/bin/env bash

# Exit if any subcommand fails
set -e
set -o pipefail

source ./script/override_shards

printf "\nChecking code formatting...\n\n"

if ! crystal tool format --check src spec > /dev/null; then
    printf "\nCode is not formatted.\n"
    printf "\nFormat the code with: crystal tool format src spec\n\n"
    exit 1
else
    printf "\nCrystal format checks passed.\n\n"
fi

if ! crystal ./bin/ameba.cr; then
    printf "\nCode did not pass Ameba checks.\n"
    printf "\nResolve Ameba linter errors, then run this checker again\n\n"
    exit 1
else
    printf "\nAmeba linter checks passed.\n\n"
fi

printf "\nRunning specs with 'crystal spec'\n\n"
crystal spec "$@"

