# This is the default pagination serializer generated by Lucky.
# Feel free to customize it in any way you like.
class PaginationSerializer < BaseSerializer
  def initialize(@pages : Lucky::Paginator)
  end

  def render
    {
      next_page:     @pages.path_to_next,
      previous_page: @pages.path_to_previous,
      total_items:   @pages.item_count,
      total_pages:   @pages.total,
    }
  end
end
