#! /bin/bash

# Exit if any subcommand fails
set -e
set -o pipefail

COMPOSE="docker-compose exec app"

docker-compose up -d

$COMPOSE shards install

printf "\nrunning specs with 'crystal spec'\n\n"
$COMPOSE crystal spec "$@"
printf "\nChecking code formatting\n\n"
if ! $COMPOSE crystal tool format --check src spec > /dev/null; then
  printf "\nCode is not formatted.\n"
  printf "\nFormat the code with: docker-compose run --rm app crystal tool format src spec\n\n"
  exit 1
fi

function finish {
    docker-compose down
}

trap finish EXIT
