#! /bin/bash

# Exit if any subcommand fails
set -e
set -o pipefail

COMPOSE="docker-compose exec app"

docker-compose up -d

$COMPOSE shards install

printf "\nrunning specs with 'crystal spec'\n\n"
$COMPOSE crystal spec "$@"
printf "\nformatting code with 'crystal tool format src spec'\n\n"
$COMPOSE crystal tool format src spec

function finish {
    docker-compose down
}

trap finish EXIT
